# Generated by Django 3.0.3 on 2020-03-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0002_auto_20200303_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='People',
        ),
    ]
