# Generated by Django 3.0.3 on 2020-03-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museu', '0004_subject_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id_person',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id_subject',
            new_name='subject',
        ),
    ]
